### ISSUE TITLE
Принимаются ли PR

### ISSUE THREAD

**Issue by sanmai** [webdenis77/cbr#2]
Поддерживается и развивается ли этот проект? В том смысле стоит ли делать PR или лучше свой форк в Composer разместить.

Что можно было бы улучшить:

- [ ] Добавить тесты
- [ ] Добавить кеш курсов (меняются раз-два в день!)
- [ ] Добавить загрузку курсов с зеркала

**Comment by webdenis77** [comment]
Добрый день. Не поддерживается и не развивается.
